# Generated by Django 4.2.7 on 2023-11-19 21:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_accounts', '0004_alter_bankcard_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MaxValueValidator(50000)])),
                ('terminal_id', models.PositiveIntegerField()),
                ('type_of', models.CharField(choices=[('re', 'refill'), ('with', 'withdrawal')], max_length=10)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_operations', to='bank_accounts.bankcard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectronicOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MaxValueValidator(50000)])),
                ('message', models.CharField(blank=True, max_length=150, null=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='send_oretations', to='bank_accounts.bankcard')),
                ('recipient_card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recepient_operation', to='bank_accounts.bankcard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
