# Generated by Django 4.2.7 on 2023-11-19 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0004_alter_bankcard_card_number'),
        ('cash_operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicoperation',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='send_oretations', to='bank_accounts.bankcard'),
        ),
        migrations.AlterField(
            model_name='terminaloperation',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_operations', to='bank_accounts.bankcard'),
        ),
    ]
