# Generated by Django 4.2.7 on 2023-11-20 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0004_alter_bankcard_card_number'),
        ('cash_operation', '0002_alter_electronicoperation_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicoperation',
            name='recipient_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepient_operation', to='bank_accounts.bankcard'),
        ),
    ]
