# Generated by Django 4.2.7 on 2023-11-18 13:07

import bank_accounts.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('freeze', 'freeze'), ('block', 'block')], default='active', max_length=10)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(validators=[bank_accounts.validators.CardNumberValidator()])),
                ('expiration_date', models.DateTimeField(validators=[bank_accounts.validators.DateValidator()])),
                ('ccv_code', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('card_type', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], max_length=6)),
                ('available', models.BooleanField(default=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='bank_accounts.bankaccount')),
            ],
        ),
    ]
