# Generated by Django 4.2.7 on 2023-11-18 13:16

import bank_accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='expiration_date',
            field=models.CharField(max_length=7, validators=[bank_accounts.validators.DateValidator()]),
        ),
    ]
