# Generated by Django 4.2.7 on 2023-11-18 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_alter_bankcard_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcard',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='bank_accounts.bankaccount'),
        ),
    ]
