# Generated by Django 4.2.7 on 2023-11-19 16:23

import bank_accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0003_bankcard_balance_alter_bankcard_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='card_number',
            field=models.CharField(validators=[bank_accounts.validators.CardNumberValidator()]),
        ),
    ]
